version: '3.0'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: canteen
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - postgres


networks:
  my-network:
    driver: bridge
